version: 2.1

executors:
  default:
    working_directory: ~/project
    docker:
      - image: circleci/node

commands:
  install_packages:
    parameters:
      cache_key:
        default: package-lock.json
        description: File to use as a Node cache checksum
        type: string
      cache_version:
        default: v1
        description: Cache version; increment this for a fresh cache
        type: string
    steps:
      - restore_cache:
          name: Restore dependencies
          key: dependencies-<< parameters.cache_version >>-{{ checksum "<< parameters.cache_key >>" }}
      - run:
          name: Install dependencies
          command: echo "package-lock=false" >> .npmrc && npm install
      - save_cache:
          name: Cache dependencies
          key: dependencies-<< parameters.cache_version >>-{{ checksum "<< parameters.cache_key >>" }}
          paths:
            - node_modules

jobs:
  test:
    executor:
      name: default
    steps:
      - checkout
      - install_packages
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Run type tests
          command: npm run typecheck

workflows:
  commit:
    jobs:
      - test
